### ISSUE TITLE
suggestion: testing instructions

### ISSUE THREAD

**Issue by iuioiua** [oslabs-beta/Deno-Redlock#33]
Hi team, I'd like to contribute to this great module. However, there aren't any testing instructions. Is it possible to have this added so contributors can do so?

**Comment by iuioiua** [comment]
Gently pinging

**Comment by iuioiua** [comment]
I am gently pinging once more. I'd love to help make this repo better! 🙂

CC @cdschexnide and @mdwatson988

**Comment by cdschexnide** [comment]
Hi @iuioiua. Sorry for the delayed response. I started a new job in October last year and we use GitLab so I'm rarely on GitHub anymore. I believe if you fork and clone the repo, you can locally make whatever changes you'd like to add. Then once you submit the pull request and one of us approves it, you'd be added as a contributor.

**Comment by iuioiua** [comment]
Great! Thank you 🙏🏾 

However, I was more referring to testing. If I make a change what test can I run to ensure I haven't broken anything?

**Comment by cdschexnide** [comment]
This is the test file: https://github.com/oslabs-beta/Deno-Redlock/blob/main/src/single.test.ts

Running this test file in the terminal will verify that your additions do not interfere with proper lock functionality.

**Comment by iuioiua** [comment]
Ah, I didn't realise there was a `src/single.test.ts`. I was using `src/testing/single.test.ts`. Thanks!
